### ISSUE TITLE
campaign logger improvements

### ISSUE THREAD

**Issue by luetkemj** [luetkemj/scribe#128]
- [x] use text area over input for logs - too small! #129 
- [x] phases of the moon #130 
- [x] auto resizing text area #131 
- [x] hide empty notes / auto pruning #132 
- [x] bulk delete notes #132 
- [x] timekeeper spins on component mount to reach current time #133
- [ ] only edit a single log at a time - disable all other edit btns
- [ ] save on enter
- [ ] improve styles on campaign log #133
- [x] drag to resize logs
- [ ] manually edit time
- [ ] hook up weather API

**Comment by luetkemj** [comment]
Delete is terrifiying! You can stack up notes to remove but you have to hit save to delete them - Delete will delete the ENTIRE LOG!

*Forgot - It's supposed to be terrifying cause I added for dev until I find a proper flow for it.

**Comment by luetkemj** [comment]
Delete note and bulk delete should be under a setting. Pruning and removal hiding of empty logs should deal with the bulk of deletion needs

**Comment by luetkemj** [comment]
sun should be a blurred yellow over a blurred white icon or a radial gradient if we have that in css...
~~Also the bug where the icon changes at midnight is back. Confirmed in the test-app not yet in app~~
